name: Check

on: [push]

jobs:
  lint_and_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint yapf
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Checking formatting of the code
      run: |
        python3 -m yapf -d $(git ls-files '*.py')
    - name: Testing on examples
      run: |
        python3 ./version.py
